### ISSUE TITLE
Code review for scripts/bootstrap + document!

### ISSUE THREAD

**Issue by lillian-lemmer** [hypatia-engine/hypatia#102]
The `script/bootstrap` file is under-documented and the code is messy. I was looking at how Travis CI uses the bootstrap script for setup now. The script is a bit confusing and unclear to me. I also noticed that it accepts arguments, in these scenarios I want to force us to use [DocOpt](http://docopt.org) (something I should probably mention in `CONTRIBUTING.md`.

**Comment by ejmr** [comment]
Pretty sure that #33 is related to this, i.e. the errors Travis-CI runs into with some of those commits are caused by some environment variables `script/bootstrap` uses.

**Comment by ejmr** [comment]
Related note, some resources I find useful for writing CLI scripts in Python:

- https://stormpath.com/blog/building-simple-cli-interfaces-in-python/
- https://github.com/rdegges/skele-cli

**Comment by lillian-lemmer** [comment]
I think the bootstrap could use a lot more objects, to reduce complicated nesting structures. N-nested dictionaries are scary.

**Comment by lillian-lemmer** [comment]
I'm thinking about rewriting `scripts/bootstrap`.

**Comment by lillian-lemmer** [comment]
ericjmritz [7:28 PM] 
IMO `scripts/bootstrap` would probably benefit best from a full rewrite.  I think that would make it easier to go back and add appropriate comments, docstrings, etc.  Which is I also think is worth it because I think having `scripts/bootstrap` is a really valuable tool for developers.
