### ISSUE TITLE
Consider Writing a pkgsrc Script

### ISSUE THREAD

**Issue by ejmr** [hypatia-engine/hypatia#106]
This would allow users and developers on systems that support [pkgsrc](http://www.pkgsrc.org/) to more easily install Hypatia.

**Comment by lillian-lemmer** [comment]
I think we've talked before about what we want to leave to the people who do actual packaging and what we want to do ourselves. I'd be up for rolling our own packages, if we automated the process through `distrib.sh`, but otherwise I think it's a waste of effort on my part.

**Comment by ibara** [comment]
I wrote one today.

**Comment by ibara** [comment]
This can be closed now. One is here: http://devio.us/~bcallah/hypatia.tgz and I have plenty of NetBSD dev friends so this'll go in. I'd close it myself but I don't have the ability to :-(

**Comment by lillian-lemmer** [comment]
Thanks @ibara that's awesome! We should have a central place for packagers... like a page on the website or something mentioning official packages? I think hat's the idea with the _Get_ page..? Closed for now. If you wanna discuss what I've mentioned open a new issue.
