### ISSUE TITLE
Python 3.5 and enum34

### ISSUE THREAD

**Issue by ejmr** [hypatia-engine/hypatia#91]
This was mentioned on Slack, but running...

    $ python setup.py install

...with Python 3.5 fails to work since the `enum34` package is not available for 3.5.  Unfortunately I don't know the best way to deal with this.  Right now I just temporarily modify `setup.py` to remove that requirement whenever I'm using Python 3.5.

**Comment by ejmr** [comment]
In `setup.py`, if we replace...

    install_requires=['pillow', 'pygame', 'enum34']

...with...

    install_requires=['pillow', 'pygame'],
    extras_require={ "enum": ["enum34"] }

...then everything works fine with regard to using Python 3.5.  My gut says this isn't the best way to deal with the problem though; it's just a temporary solution.  Maybe our `scripts/bootstrap` could deal with whether or not to install `enum34`.

**Comment by lardnar** [comment]
So in bootstrap we have the special_cases table

Is it reasonable to:
* have a version_cases table, 
* include in it a case for python2, python3-but-not-3.5, and python3.5, 
* make a new requirements file for python3.5 that doesn't include enum34

Or something along those lines?

**Comment by alxcenz** [comment]
I believe the special_cases already lets you match against versions, all
that would need to be done is make it allow multiple special cases to be
run in one install (it only runs the first matching one atm)

**Comment by lardnar** [comment]
Makes sense. I have basically no ability to do testing on other platforms, so I was hoping to change the codepath as little as possible, but that's probably a better way to close this overall.

**Comment by lillian-lemmer** [comment]
`install_requires` caused problems with python 3.5, see above referenced issue. it was fixed in time for the halloween release. If anyone wants to implement `extras_require` and test it in Python 3.5 *and* 2 *before* making a pull request, I'd really appreciate that. Although, how much does this double our effort? I like using the pip requirements files and what's the advantage of also specifying the requirements in `setup.py` considering this is the approach? Perhaps, I should not be using this approach? In my opinion, it is the simplest.

**Comment by ejmr** [comment]
> If anyone wants to implement extras_require and test it in Python 3.5 and 2 before making a pull request, I'd really appreciate that.

Tested on commit 065989847dc183973be22af182246c8d4e13eed9.

Using Python 3.5 works fine.  Using Python 2.7 works as well, specifically:

    pip 7.1.2 from /usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg (python 2.7)

**Comment by lillian-lemmer** [comment]
I will be resolving this issue soon by simply detecting the PYthon version and conditionally building/setting install_requires.

**Comment by lillian-lemmer** [comment]
This has been resolved.
