### ISSUE TITLE
pypi readme not showing up

### ISSUE THREAD

**Issue by lillian-lemmer** [hypatia-engine/hypatia#98]
probably because it included some banned markup

**Comment by lillian-lemmer** [comment]
https://pypi.python.org/pypi/hypatia_engine/ It still isn't working. :/ Any ideas why?

Here's the latest release: https://github.com/hypatia-engine/hypatia/releases/tag/0.3.1

**Comment by SanketDG** [comment]
Uh, Sorry, I thought you had set `long_description` in `setup.py`. Can you try that:
```
long_description=open('README.md').read()
```

If this doesn't work, you are better using [setuptools-markdown](https://pypi.python.org/pypi/setuptools-markdown)

**Comment by lillian-lemmer** [comment]
@SanketDG why would i have a config that specifies the readme/package desc, and an argument that does as well in setup.py?

I will try that and look at the link provided.

**Comment by lillian-lemmer** [comment]
@SanketDG this is what happens if I set `long_description` in `setup.py` to the code you supplied https://testpypi.python.org/pypi?:action=display&name=hypatia_engine&version=0.3.2

**Comment by lillian-lemmer** [comment]
I figured it out. Preparing for 0.3.2 release.

**Comment by SanketDG** [comment]
@lillian-lemmer Cool!

**Comment by lillian-lemmer** [comment]
Thanks for your help.
